### PR TITLE
rfct(crates/lang_unicodes): migrate to opencc-rust

### LINKED ISSUE #114: discussion: improve the rust part
### strip nodejs as build dependency

If you would like to get rid of the nodejs scripts to pre-process the data, I have written the crate `lang_unicodes` in rust. It uses opencc instead of `chinese-simple2traditional` but make the build environment more complex. I'm glad to open a PR about it if you like the idea.

Link: https://github.com/Cryolitia/yet-another-lang-unicodes-rs

### shell completion and manpage

We could use `clap_autocomplete` and `clap_mangen` to provide these, which have been already widely uses in other rust cli tools.

### PR DESCRIPTION
**Pull request by Cryolitia**
close https://github.com/KonghaYao/cn-font-split/issues/114

test log: https://github.com/Cryolitia-Forks/cn-font-split/actions/runs/12525425493/job/34936972392

## Summary by Sourcery

Migrate the crates/lang_unicodes crate to use opencc-rust.

Build:
- Install opencc in the CI build process.

CI:
- Update CI scripts to install necessary dependencies, including opencc, for different operating systems (Windows, Linux, macOS).

### CODE REVIEW

**Comment by KonghaYao** [comment]
image
I have performed an initial code review of your code, but opencc got stuck for a very long time without responding on my Mac Mini M2. I suspect that it is caused by an issue with the invocation of opencc, and there is also an error in the format of cross_build.yml. Can this be fixed? @Cryolitia

**Comment by Cryolitia** [comment]
The step of calling opencc(throw spawn) costs the most of the time. On typical macOS machines it will be around 4 minutes. An alternative solution is to use the `opencc-rust` crate, which is significant faster. The problem is that we don't have a simple work-out-of-box pkg-config on Windows, also the crate `opencc-rust` is not designed for Windows, so it's hard to build it on it.

Probably we could use `opencc-rust` on macOS and Linux, and directly call opencc on Windows.

**Comment by KonghaYao** [comment]
Considering that lang_unicode only needs to be built during the build process, perhaps we can use native bindings (if opencc is consistent across platforms). It seems that [opencc-sys](https://github.com/novel-rs/opencc-rs/blob/main/opencc-sys/src/lib.rs) has done some work in this area, with fewer dependencies, so it might be worth trying. @Cryolitia

**Comment by Cryolitia** [comment]
@KonghaYao update

**Pull request merged**
